server:
  port: 31400
spring:
  application:
    name: xc-service-manage-media
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: xc_media
xc-service-manage-media:
  upload-location: E:/学成在线/xcEdu/xcVideo/
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
eureka:
  client:
    register-with-eureka: true  #服务注册开关
    fetch-registry: true  #服务发现开关
    service-url:  #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: http://localhost:50101/eureka/
  instance:
    prefer-ip-address: true  #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id
ribbon:
  MaxAutoRetries: 2  #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现等的情况下是很危险的,所以设置为false
  ConnecTimeout: 5000 #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间 
